### ISSUE TITLE
mulitple local ports separated with commas

### ISSUE THREAD

**Issue by lizyu1** [GeoffWilliams/puppet-windows_firewall#11]
Hi Geoff,

Any update on the script to support multiple local ports in Windows server 2016?

Here is the Hiera lookup node variables:

windows_fw::enablefw::rules:
   'Proxy-Service':
     direction: 'inbound'
     action: 'allow'
     protocol: 'tcp'
     local_port: ['80','443','4243']
     remote_address: 'any'
     remote_port: 'any'
     description: 'Proxy-Service'

Error

Notice: /Stage[main]/Windows_fw::Enablefw/Windows_firewall_rule[Proxy-Service]/local_port: local_port changed '80' to '80,443,4243'
Notice: (windows_firewall) deleting rule 'Proxy-Service'
Notice: (windows_firewall) adding rule 'Proxy-Service'
Error: /Stage[main]/Windows_fw::Enablefw/Windows_firewall_rule Proxy-Service]: Could not evaluate: Execution of 'powershell.exe -ExecutionPolicy Bypass -File C:/ProgramData/PuppetLabs/puppet/cache/lib/ps/windows_firewall/ps-bridge.ps1 create -Name Qlik Sense Proxy-Service -Enabled True -DisplayName Proxy-Service -Description Proxy-Service -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort "80,443,4243" -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any' returned 1: New-NetFirewallRule : The port is invalid.  When Protocol is TCP or UDP, individual ports or ranges are allowed.
Also, the following port keywords are allowed on Firewall Rules: RPC, RPCEPMap, Teredo, IPHTTPSIn, IPHTTPSOut,
PlayToDiscovery.
At C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall\ps-bridge.ps1:422 char:5

The below commands reported the same error as above.

PS C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall> ps-bridge.ps1 create -Name "Schedule-Service" -Enabled True -DisplayName "Scheduler-Service" -Description "Schedule-Service" -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort "5050", "5151", "5252" -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any

PS C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall> ps-bridge.ps1 create -Name "Schedule-Service" -Enabled True -DisplayName  Scheduler-Service" -Description "Schedule-Service" -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort 5050, 5151, 5252 -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any

PS C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall> ps-bridge.ps1 create -Name "Schedule-Service" -Enabled True -DisplayName " Scheduler-Service" -Description "Schedule-Service" -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort "5050,5151,5252" -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any

Regards,
Liz

**Comment by GeoffWilliams** [comment]
Hi Liz,

Thanks for your report. If you need an immediate workaround, I'd suggest just creating individual rules for each port - that should unblock you.

The `ps-pbridge.ps1` script uses `new-netfirewallrule` and this command supports the kind of port ranges you want to set. In the script the `localPort` parameter is a `String` but according to https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps it should be `String[]`.

So the parts to fix on this would be:
* Puppet type and provider (ruby)
* Powershell script (set value and read value)

```ps-bridge.ps1 create -Name "Schedule-Service" -Enabled True -DisplayName "Scheduler-Service" -Description "Schedule-Service" -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort "5050", "5151", "5252" -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any```

most closely matches the examples in the powershell docs - I think changing `LocalPort` script parameter to be `String[]` might allow this to work? If it doesn't - might also need to use parentheses when the parameter is passed to `new-netfirewallrule` (see - https://stackoverflow.com/a/7153001)/3441106)

**Comment by lizyu1** [comment]
Hi Geoff,

We already implemented individual rules for each port as a workaround. They work.

The command you suggested doesn't work.

`ps-bridge.ps1 create -Name "Schedule-Service" -Enabled True -DisplayName "Scheduler-Service" -Description "Schedule-Service" -Direction Inbound -RemoteAddress "Any" -Protocol TCP -LocalPort "5050", "5151", "5252" -RemotePort "Any" -EdgeTraversalPolicy Block -Action Allow -InterfaceType Any` 

New-NetFirewallRule : The port is invalid.  When Protocol is TCP or UDP, individual ports or ranges are allowed.  Also, the 
following port keywords are allowed on Firewall Rules: RPC, RPCEPMap, Teredo, IPHTTPSIn, IPHTTPSOut, PlayToDiscovery.
At C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall\ps-bridge.ps1:422 char:5
     New-NetFirewallRule @params -ErrorAction Stop
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (MSFT_NetFirewallRule:root/standardcimv2/MSFT_NetFirewallRule) [New-NetFirewallRule], 
    CimException
     FullyQualifiedErrorId : HRESULT 0x80070057,New-NetFirewallRule



New-NetFirewallRule command works fine.

Example:
`New-NetFirewallRule -DisplayName "Allow TCP 12345 and 5000-5020 over Teredo" -Direction Inbound -Action Allow -EdgeTraversalPolicy Allow -Protocol TCP -LocalPort 12345,234-345 -Program "C:\Program Files (x86)\ManageSoft\Launcher\reboot"`

It creates port 12345, 234-345 as expected.

Regards,
Liz

**Comment by GeoffWilliams** [comment]
thanks for checking - if i get some time over the next couple of weeks I'll see what I can do to fix this

**Comment by lizyu1** [comment]
Thanks Geoff!
