### ISSUE TITLE
Multiple remote addresses or ranges

### ISSUE THREAD

**Issue by trenta** [GeoffWilliams/puppet-windows_firewall#15]
I was wondering if this module handles multiple remote addresses or ranges in a similar fashion to ports.

I'm getting the following error.  Redacted a couple of things with xx

```
Error: /Stage[main]/xxx/Windows_firewall_rule[Fileserver File and Printer Sharing TCP]: Could not evalua
te: Execution of 'powershell.exe -ExecutionPolicy Bypass -File C:/ProgramData/PuppetLabs/puppet/cache/lib/ps/windows_fir
ewall/ps-bridge.ps1 create -Name Fileserver File and Printer Sharing TCP -Enabled True -DisplayName Fileserver File and
Printer Sharing TCP -Description Inbound rule for Fileserver for File and Printer sharing. [TCP 139,445] -Direction Inbo
und -RemoteAddress "xx.xx.0.0/24,xx.xx.0.0/24" -Protocol TCP -LocalPort "139,445" -RemotePort "Any" -EdgeTraversalPolic
y Block -Action Allow -InterfaceType Any' returned 1: New-NetFirewallRule : The address is invalid.  Addresses may be sp
ecified as IP addresses, ranges, or subnets.  Also,
the following address keywords are allowed in certain places: LocalSubnet, DNS, DHCP, WINS, DefaultGateway, Internet,
Intranet, IntranetRemoteAccess, PlayToDevice.  Keywords can be restricted to IPv4 or IPv6 by appending a 4 or 6.
At C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall\ps-bridge.ps1:426 char:5
+     New-NetFirewallRule @params -ErrorAction Stop
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MSFT_NetFirewallRule:root/standardcimv2/MSFT_NetFirewallRule) [New-Net
   FirewallRule], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,New-NetFirewallRule
```

**Comment by GeoffWilliams** [comment]
@trenta `remote_address` should be passed straight through to powershell as a string where it gets picked up by [`New-NetFirewallRule`](https://docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=win10-ps)

Allowed inputs are:
>    Single IPv4 Address: 1.2.3.4
>   Single IPv6 Address: fe80::1
>    IPv4 Subnet (by network bit count): 1.2.3.4/24
>    IPv6 Subnet (by network bit count): fe80::1/48
>    IPv4 Subnet (by network mask): 1.2.3.4/255.255.255.0
>    IPv4 Range: 1.2.3.4-1.2.3.7
>    IPv6 Range: fe80::1-fe80::9
>    Keyword: Any, LocalSubnet, DNS, DHCP, WINS, DefaultGateway, Internet, Intranet, IntranetRemoteAccess, PlayToDevice. NOTE: Keywords can be restricted to IPv4 or IPv6 by appending a 4 or 6 (for example, keyword "LocalSubnet4" means that all local IPv4 addresses are matching this rule).

What happens if you remove/use only the subnet? eg one of:

```puppet
remote_address => "xx.xx.0.1-xx.xx.0.99" # I wonder if .0 (network) addresses are not allowed in ranges too...

remote_address=> "xx.xx.0.0/24" # whole subnet
```

**Comment by trenta** [comment]
Thanks for the response and the command you are using.  Reading up a bit on that seems that it can only take a single entry be it a range or single ip.  So I might have to do multiple rules.

**Comment by GeoffWilliams** [comment]
no probs - I'll close this ticket then since it seems to be either workaroundable or a limitation of the underlying powershell
