### ISSUE TITLE
Usage of multiple IP's for Address not working

### ISSUE THREAD

**Issue by jpatigny** [GeoffWilliams/puppet-windows_firewall#18]
Hello,

First of all, thank you for making this module.
I've been testing it and I see that it's currently not possible to pass multiple IP's to the RemoteAddress and LocalAddress parameters.

I know that it's possible with the cmdlet new-netfirewallrule that you are usinbg by passing an array of IP's. (refer to https://stackoverflow.com/questions/35366963/powershell-script-to-add-multiple-remote-address-to-firewall-rules/35367349)

I'm trying to adapt it myself in the ps-bridge-create.ps1 script but I'm not sure that it's gonna be enough. 
As i'm not skilled at all in ruby i'd like to know if there is anything to adapt in the ruby part

Thanks for your feedback.

**Comment by GeoffWilliams** [comment]
You would also need to update the puppet (ruby) type and provider to account for passing an array. I think I did something similar for ranges of ports (see recent pull requests). I'm not actively working on Puppet stuff at the moment but happy to review a PR if you come up with something

**Comment by jpatigny** [comment]
So...I was able to cheat a little bit. I kept the parameter type as a string and I'm passing a list of IP separeated by a coma.

I adapted the powershell script (create function) to convert the string to an array if it match a coma in the string and it's working : 

`# Host filter
    if ($LocalAddress) {
        if ($LocalAddress -match ",") {
            [array]$LocalAddressArray = $LocalAddress.split(',')
            $params.Add("LocalAddress", $LocalAddressArray)
        } else {
            $params.Add("LocalAddress", $LocalAddress)
        }
    }
    if ($RemoteAddress) {
        if ($RemoteAddress -match ",") {
            [array]$RemoteAddressArray = $RemoteAddress.split(',')
            $params.Add("RemoteAddress", $RemoteAddressArray)
        } else {
            $params.Add("RemoteAddress", $RemoteAddress)
        }
    }`

The consequence of this is that the config is reapplied at every puppet run because the output of the show is different to what is set in the manifest.

`[xxxxxxx]: PS C:\Users\jpatigny\Documents> powershell.exe -ExecutionPolicy Bypass -File C:/ProgramData/PuppetLabs/puppet/cache/lib/ps/windows_firewall/ps-bridge.ps1 show                                                                              [
    {
        "Action":  "Allow",
        "Description":  "",
        "Direction":  "Inbound",
        "Name":  "002 allow RDP",
        "EdgeTraversalPolicy":  "Block",
        "Unused_RuleSource":  "Local Setting",
        "RemotePort":  "Any",
        "LocalAddress":  "Any",
        "Protocol":  "TCP",
        "LocalPort":  "3389",
        "DisplayGroup":  "",
        "InterfaceType":  "Any",
        "IcmpType":  null,
        "Unused_Security":  "NotRequired",
        "DisplayName":  "002 allow RDP",
        "Profile":  "Domain,Private,Public",
        "RemoteAddress":  "10.133.6.107-10.133.6.107,10.133.6.110-10.133.6.110,10.133.6.186-10.133.6.186,10.133.6.202-10.133.6.202,10.133.6.206-10.133.6.206,10.133.6.22-10.133.6.22,10.133.6.221-10.133.6.221,10.133.6.223-10.133.6.223,10.133.6.238-10.133.6.238,10.133.6.243-10.133.6.243,10.133.6.50-10.133.6.50,10.133.6.51-10.133.6.51,10.133.6.72-10.133.6.72,10.133.6.90-10.133.6.90,10.133.6.99-10.133.6.99,10.135.6.182-10.135.6.182,10.135.6.23-10.135.6.23,10.135.6.237-10.135.6.237,10.135.6.50-10.135.6.50,10.135.6.51-10.135.6.51,10.135.6.54-10.135.6.54,10.135.6.87-10.135.6.87,10.137.6.141-10.137.6.141,10.137.6.184-10.137.6.184,10.137.6.50-10.137.6.50,10.137.6.51-10.137.6.51,10.137.6.64-10.137.6.64,10.137.6.85-10.137.6.85",
        "Enabled":  "True"
    },`

I'm still digging :)

**Comment by Hvid** [comment]
Hi,

I submitted https://github.com/GeoffWilliams/puppet-windows_firewall/pull/21

Seems to work for me. Please have a look.

**Comment by GeoffWilliams** [comment]
fix released as v0.5.0 :beers:
