### ISSUE TITLE
port not applicable on icmp firewall rules

### ISSUE THREAD

**Issue by TomG83** [GeoffWilliams/puppet-windows_firewall#22]
Hello,

I had this as firewall rule in hieradata:

    'Puppet: ping IPv4 - allow any ip':
        ensure: present
        direction: 'inbound'
        action: 'allow'
        enabled: true
        protocol: 'icmpv4'
        remote_port: 'any'
        display_name: 'Puppet: ping IPv4 - allow any ip'
        description: 'Allow icmpv4 connections'

Mentioning a port, makes the rule every time being re-created upon every Puppet agent run like this:

Notice: /Stage[main]/Base_software_win::Manage_firewall/Windows_firewall_rule[Puppet: ping IPv4 - allow any ip]/remote_port: defined 'remote_port' as 'any' (corrective)
Notice: (windows_firewall) deleting rule 'Puppet: ping IPv4 - allow any ip'
Notice: (windows_firewall) adding rule 'Puppet: ping IPv4 - allow any ip'

As one can see in the Windows firewall advanced rules interface, local and remote port options are greyed out when using icmp as protocol type.

When removing the remote_port, no more changes are applied on a Puppet agent run

**Comment by GeoffWilliams** [comment]
ICMP is a separate network layer to TCP/UDP and doesn't use ports. Try this hiera data instead:

```
'Puppet: ping IPv4 - allow any ip':
    ensure: present
    direction: 'inbound'
    action: 'allow'
    enabled: true
    protocol: 'icmpv4'
    display_name: 'Puppet: ping IPv4 - allow any ip'
    description: 'Allow icmpv4 connections'
```
