### ISSUE TITLE
New-NetFirewallRule : Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by TomG83** [GeoffWilliams/puppet-windows_firewall#23]
Hello,

We have some issues with a couple of firewall rules:

1. Upon the first Puppet agent run, the rule is created just fine
2. Upon Puppet agent run's afterwards, errors, it looks like the rule will be created again (which fails, because it already exitsts).

Error:

> ... returned 1: New-NetFirewallRule : Cannot create a file when that file already exists.
> At C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall\ps-bridge.ps1:431 char:5
> +     New-NetFirewallRule @params -ErrorAction Stop
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceExists: (MSFT_NetFirewallRule:root/standardcimv2/MSFT_NetFirewallRule) [New-NetFirewallRule], CimException
>     + FullyQualifiedErrorId : Windows System Error 183,New-NetFirewallRule

Hieradata firewall rules:

    'Puppet: CANONIWMC - EventSentry Service ports':
        ensure: present
        direction: 'inbound'
        action: 'allow'
        enabled: true
        protocol: 'tcp'
        local_port: '5050,5051,5055,1433'
        remote_port: 'any'
        remote_address: 'any'
        display_name: 'Puppet: CANONIWMC - EventSentry Service Ports'
        description: 'Allow CANONIWMC - EventSentry Service Ports'

    'Puppet: CANONIWMC - IWMC Service ports':
        ensure: present
        direction: 'inbound'
        action: 'allow'
        enabled: true
        protocol: 'tcp'
        local_port: '80,443,389,25,110,427,161,53,137,8080,11427,3702,5355,47545'
        remote_port: 'any'
        remote_address: 'any'
        display_name: 'Puppet: CANONIWMC - IWMC Service Ports'
        description: 'Allow CANONIWMC - IWMC Service Ports'

Something wrong in our hieradata?

**Comment by GeoffWilliams** [comment]
Looks like it could be the port order not matching what what powershell is reporting. What happens if your sort your ports lowest -> highest in your hiera data? eg:

```
    local_port: '1433,5050,5051,5055'
```

You can check how rules are viewed by puppet with `puppet resource windows_firewall_rule` on the node having problems.

**Comment by TomG83** [comment]
I've re-orderd the rules van lowest to highest, but unfortunatelly still same issue (also when deleting rules by hand and doing 2 Puppet agent runs, problem re-occurs starting second Puppet agent run).

Output of puppet resource windows_firewall_rule for problem rules this time:

```
windows_firewall_rule { 'Puppet: CANONIWMC - EventSentry Service Ports':
  ensure                => 'present',
  action                => 'allow',
  description           => 'Allow CANONIWMC - EventSentry Service Ports',
  direction             => 'inbound',
  display_name          => 'Puppet: CANONIWMC - EventSentry Service Ports',
  edge_traversal_policy => 'block',
  enabled               => 'true',
  interface_type        => ['any'],
  local_address         => 'any',
  local_port            => '1433,5050,5051,5055',
  profile               => ['domain', 'private', 'public'],
  protocol              => 'tcp',
  remote_address        => 'any',
  remote_port           => 'any',
}
windows_firewall_rule { 'Puppet: CANONIWMC - IWMC Service Ports':
  ensure                => 'present',
  action                => 'allow',
  description           => 'Allow CANONIWMC - IWMC Service Ports',
  direction             => 'inbound',
  display_name          => 'Puppet: CANONIWMC - IWMC Service Ports',
  edge_traversal_policy => 'block',
  enabled               => 'true',
  interface_type        => ['any'],
  local_address         => 'any',
  local_port            => '25,53,80,110,137,161,389,427,443,3702,5355,8080,11427,47545',
  profile               => ['domain', 'private', 'public'],
  protocol              => 'tcp',
  remote_address        => 'any',
  remote_port           => 'any',
}
```

**Comment by GeoffWilliams** [comment]
Maybe its not the port field that's causing this (my first guess)? I would try commenting out all of the parameters in your hiera data for one of the rules and gradually re-introduce them until you can isolate the parameter that causes the problem. Hopefully this will give you an easy fix, otherwise I'm not working on puppet modules at the moment but happy to take a look if you come up with a PR to fix this yourself

**Comment by TomG83** [comment]
We found the issue ...

apparently, the resource name, display_name and description was copy/pasted from somewhere else (e-mail, Word document,..). That seemed to have some characters issues (quoting character, comma and some non-printing characters). Manually chaging those solved the problem. :)

**Comment by GeoffWilliams** [comment]
That would do it! - thanks for the update, I'll close this
