### ISSUE TITLE
[feature] support for named port numbers

### ISSUE THREAD

**Issue by roniyako** [GeoffWilliams/puppet-windows_firewall#8]
Example Rule that keeps getting re added below.

Puppet code

    'Windows Firewall Remote Management (RPC-EPMAP)':
      direction: 'inbound'
      action: 'allow'
      protocol: 'tcp'
      local_port: 'rpcepmap'
      remote_address: 'any'
      remote_port: 'any'
      program: 'c:\windows\system32\svchost.exe'
      description: 'Windows Firewall Remote Management (RPC-EPMAP)'

Notice: /Stage[main]/Windows_fw::Enablefw/Windows_firewall_rule[Windows Firewall Remote Management (RPC-EPMAP)]/local_port: local_port changed 'rpc-epmap' to 'rpcepmap'
Notice: (windows_firewall) deleting rule 'Windows Firewall Remote Management (RPC-EPMAP)'
Notice: (windows_firewall) adding rule 'Windows Firewall Remote Management (RPC-EPMAP)'
Notice: Applied catalog in 54.10 seconds

Rule from my server

PS K:\> (get-NetFirewallRule -Name 'Windows Firewall Remote Management (RPC-EPMAP)')

Name                  : Windows Firewall Remote Management (RPC-EPMAP)
DisplayName           : Windows Firewall Remote Management (RPC-EPMAP)
Description           : Windows Firewall Remote Management (RPC-EPMAP)
DisplayGroup          : 
Group                 : 
Enabled               : True
Profile               : Any
Platform              : {}
Direction             : Inbound
Action                : Allow
EdgeTraversalPolicy   : Block
LooseSourceMapping    : False
LocalOnlyMapping      : False
Owner                 : 
PrimaryStatus         : OK
Status                : The rule was parsed successfully from the store. (65536)
EnforcementStatus     : NotApplicable
PolicyStoreSource     : PersistentStore
PolicyStoreSourceType : Local

PS K:\> (get-NetFirewallRule -Name 'Windows Firewall Remote Management (RPC-EPMAP)') | Get-NetFirewallPortFilter

Protocol      : TCP
LocalPort     : RPCEPMap
RemotePort    : Any
IcmpType      : Any
DynamicTarget : Any

**Comment by GeoffWilliams** [comment]
looks like a miss-match between powershell and `netsh`. I bet `netsh advfirewall firewall show rule Windows Firewall Remote Management (RPC-EPMAP)`"  lists `rpc-epmap`.

Need to add support for:
* rpc dynamic ports
* rpc endpoint mapper
* iphttps

**Comment by GeoffWilliams** [comment]
only applies to local ports

**Comment by GeoffWilliams** [comment]
Names map as follows:

| UI | PS | netsh|
| --- | --- | --- |
| RPC dynamic ports |RPC | RPC |
| RPC Endpoint Mapper | RPCEPMap | RPC-EPMap|
| IP HTTPS | IPHTTPSIn | IPHTTPS |

**Comment by GeoffWilliams** [comment]
in progress, also:
RemotePort needs mapping:

|UI | PS | netsh|
|---|---|---|
|IP HTTPS |  IPHTTPSOut | IPHTTPS|

**Comment by GeoffWilliams** [comment]
fixed in bf1335a
