### ISSUE TITLE
Error accessing HKEY_CLASSES_ROOT after first logon

### ISSUE THREAD

**Issue by canihavethisone** [GeoffWilliams/puppet-windows_firewall#9]
Hardening Win10.1809 LTSC

Using the following code in manifest that references a hiera hash.  Blocking and purging everything except what I specify in hiera (total of 9 outbound and 3 inbound rules):
`        class profiles::myclass (
Hash     $firewall_rules = lookup('profiles::myclass::firewall', {merge => 'hash'}),
){
  windows_firewall_profile { ['domain', 'private', 'public']:
    state                      => 'on',
    inboundusernotification    => 'enable',
    firewallpolicy             => 'blockinbound,blockoutbound',
    logallowedconnections      => 'disable',
    logdroppedconnections      => 'enable',
    maxfilesize                => '4096',
    unicastresponsetomulticast => 'disable',
  }

  resources { "windows_firewall_rule":
    purge => true,
  }

  $firewall_rules.each |$key, $value| {
    windows_firewall_rule {
    default:
    ensure                => 'present',
    action                => 'allow',
    enabled               => 'true',
    edge_traversal_policy => 'block',
    local_address         => $facts[networking][ip],
    ;
    $key:
    * => $value,
    ;
    }
  }
}
`

It applies prior to logon, (occasional error on first run, will report separately if persistent), and then after logon I always get the following error on first puppet run:

`    Failed to generate additional resources using 'generate': Execution of 'powershell.exe -ExecutionPolicy Bypass -File C:/ProgramData/PuppetLabs/puppet/cache/lib/ps/windows_firewall/ps-bridge.ps1 show' returned 1: could not resolve @{Microsoft.Windows.ContentDeliveryManager_10.0.17763.1_neutral_neutral_cw5n1h2txyewy?ms-resource://M
icrosoft.Windows.ContentDeliveryManager/resources/AppDisplayName} in registry under HKCR:\Local Settings\MrtCache
At C:\ProgramData\PuppetLabs\puppet\cache\lib\ps\windows_firewall\ps-bridge.ps1:98 char:13
throw "could not resolve $($ref) in registry under $($sea ...
CategoryInfo : OperationStopped: (could not resol...ttings\MrtCache:String) [], RuntimeException
FullyQualifiedErrorId : could not resolve @{Microsoft.Windows.ContentDeliveryManager_10.0.17763.1_neutral_neutra 
l_cw5n1h2txyewy?ms-resource://Microsoft.Windows.ContentDeliveryManager/resources/AppDisplayName} in registry under 
HKCR:\Local Settings\MrtCache` 

Puppet then continues to run with this error.

**Comment by canihavethisone** [comment]
Also getting this error intermittently:
`    Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/windows_firewall_profile: Could not autoload puppet/provider/windows_firewall_profile/ruby: no such file to load -- puppet_x/windows_firewall (file: /etc/puppetlabs/code/environments/production/site/profiles/manifests/myclass.pp, line: 154, column: 3) on node ...`

**Comment by canihavethisone** [comment]
The issue here _appears_ to perhaps be the account that Puppet Runs as (local system).  If I run 'puppet agent -t' from an elevated prompt it works without error accessing HKCR.  At elevated prompt I can also successfully run the commands that appear to error in ps-bridge.ps1 if it runs as local system after a user account has logged on:

    `  New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT
       Get-ChildItem 'HKCR:\Local Settings\MrtCache' -rec -ea SilentlyContinue `

However, the intermittent error of 'Could not autoload puppet/provider/windows_firewall_profile/ruby: no such file to load' still occurs, infrequently and at random.

**Comment by GeoffWilliams** [comment]
thanks for your bug report, #10 duplicates this and was fixed yesterday.

fix released in v0.2.4

**Comment by GeoffWilliams** [comment]
the powershell/loading issues merit separate tickets if still a problem.

Please also try restarting your puppet master, I've had issues with cached versions of different modules in the past. Ruby loading errors like the one you describe should be 100% reproducible given an identical environment so suspect caching at this stage
